openapi: 3.0.1
info:
  title: monster-vrock
  x-cortex-tag: monster-vrock
  x-cortex-custom-metadata:
    alignment: lawful-neutral
    type: ooze
    challenge_rating: 14
    legendary: false
    armor_class: 19
    hit_points: 227
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-vrock
      alias: github-token-test
